"""UC03 - Metadata tagging and naming convention

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc03]


@pytest.mark.workbook_id("UC03-FT001")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft001(case_runner):
    """UC03-FT001: Save evidence with complete metadata"""
    case_runner("UC03-FT001")


@pytest.mark.workbook_id("UC03-FT002")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft002(case_runner):
    """UC03-FT002: Enforce mandatory tagging fields"""
    case_runner("UC03-FT002")


@pytest.mark.workbook_id("UC03-FT003")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft003(case_runner):
    """UC03-FT003: Apply naming convention"""
    case_runner("UC03-FT003")


@pytest.mark.workbook_id("UC03-FT004")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft004(case_runner):
    """UC03-FT004: Reject invalid naming pattern"""
    case_runner("UC03-FT004")


@pytest.mark.workbook_id("UC03-FT005")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft005(case_runner):
    """UC03-FT005: Validate controlled tag values"""
    case_runner("UC03-FT005")


@pytest.mark.workbook_id("UC03-FT006")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft006(case_runner):
    """UC03-FT006: Edit metadata with audit history"""
    case_runner("UC03-FT006")


@pytest.mark.workbook_id("UC03-FT007")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc03_ft007(case_runner):
    """UC03-FT007: Search using metadata tags"""
    case_runner("UC03-FT007")


@pytest.mark.workbook_id("UC03-FT008")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc03_ft008(case_runner):
    """UC03-FT008: Preserve metadata across restart"""
    case_runner("UC03-FT008")


@pytest.mark.workbook_id("UC03-FT009")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc03_ft009(case_runner):
    """UC03-FT009: Validate role-based access for Metadata tagging and naming convention"""
    case_runner("UC03-FT009")


@pytest.mark.workbook_id("UC03-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc03_ft010(case_runner):
    """UC03-FT010: Validate notification mechanism for Metadata tagging and naming convention"""
    case_runner("UC03-FT010")


@pytest.mark.workbook_id("UC03-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc03_ft011(case_runner):
    """UC03-FT011: Validate integration flow for Metadata tagging and naming convention"""
    case_runner("UC03-FT011")


@pytest.mark.workbook_id("UC03-FT012")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc03_ft012(case_runner):
    """UC03-FT012: Validate retry and recovery for Metadata tagging and naming convention"""
    case_runner("UC03-FT012")


@pytest.mark.workbook_id("UC03-FT013")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc03_ft013(case_runner):
    """UC03-FT013: Validate security controls for Metadata tagging and naming convention"""
    case_runner("UC03-FT013")


@pytest.mark.workbook_id("UC03-FT014")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc03_ft014(case_runner):
    """UC03-FT014: Validate evidence integrity for Metadata tagging and naming convention"""
    case_runner("UC03-FT014")


@pytest.mark.workbook_id("UC03-FT015")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc03_ft015(case_runner):
    """UC03-FT015: Validate concurrent user operations for Metadata tagging and naming convention"""
    case_runner("UC03-FT015")


@pytest.mark.workbook_id("UC03-FT016")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc03_ft016(case_runner):
    """UC03-FT016: Validate dashboard/report visibility for Metadata tagging and naming convention"""
    case_runner("UC03-FT016")


@pytest.mark.workbook_id("UC03-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc03_ft017(case_runner):
    """UC03-FT017: Validate retention and archival for Metadata tagging and naming convention"""
    case_runner("UC03-FT017")
