import {
  Box,
  Chip,
  Dialog,
  DialogContent,
  IconButton,
  Typography,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import DescriptionIcon from '@mui/icons-material/Description';
import TableChartIcon from '@mui/icons-material/TableChart';
import CodeIcon from '@mui/icons-material/Code';
import ImageIcon from '@mui/icons-material/Image';
import { colors } from '../../theme/colors';
import type { ApprovalStatus, Artifact, ArtifactFileType } from '../../types/artifacts';

const fileIcons: Record<ArtifactFileType, typeof DescriptionIcon> = {
  docx: DescriptionIcon,
  xlsx: TableChartIcon,
  yaml: CodeIcon,
  png: ImageIcon,
};

const statusColors: Record<ApprovalStatus, string> = {
  Approved: colors.success,
  'Pending Review': colors.warning,
  Draft: colors.info,
  Rejected: colors.critical,
};

function SectionTitle({ children }: { children: string }) {
  return (
    <Typography
      variant="caption"
      sx={{
        fontWeight: 700,
        color: colors.secondary,
        textTransform: 'uppercase',
        letterSpacing: '0.06em',
        fontSize: '0.65rem',
        display: 'block',
        mb: 1,
      }}
    >
      {children}
    </Typography>
  );
}

function MetaField({ label, value }: { label: string; value: string }) {
  return (
    <Box>
      <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem', display: 'block' }}>
        {label}
      </Typography>
      <Typography variant="body2" sx={{ fontSize: '0.78rem', fontWeight: 600 }}>
        {value}
      </Typography>
    </Box>
  );
}

interface ArtifactDetailModalProps {
  artifact: Artifact | null;
  open: boolean;
  onClose: () => void;
}

export function ArtifactDetailModal({ artifact, open, onClose }: ArtifactDetailModalProps) {
  if (!artifact) return null;

  const statusColor = statusColors[artifact.approvalStatus];
  const FileIcon = fileIcons[artifact.fileType];

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      slotProps={{
        paper: {
          sx: {
            background: `linear-gradient(180deg, ${colors.bg.tertiary} 0%, ${colors.bg.primary} 100%)`,
            border: `1px solid ${colors.border.subtle}`,
            borderRadius: 2,
            boxShadow: `0 8px 32px rgba(0,0,0,0.5)`,
          },
        },
        backdrop: {
          sx: { backgroundColor: 'rgba(4, 11, 31, 0.65)' },
        },
      }}
    >
      <Box
        sx={{
          p: 2,
          borderBottom: `1px solid ${colors.border.subtle}`,
          display: 'flex',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
          gap: 1,
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <FileIcon sx={{ color: colors.primary, fontSize: 22 }} />
          <Box>
            <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem', textTransform: 'uppercase' }}>
              Generated Artifact
            </Typography>
            <Typography variant="subtitle1" sx={{ fontWeight: 700, lineHeight: 1.3 }}>
              {artifact.name}
            </Typography>
          </Box>
        </Box>
        <IconButton size="small" onClick={onClose} sx={{ color: colors.text.secondary }}>
          <CloseIcon fontSize="small" />
        </IconButton>
      </Box>

      <DialogContent sx={{ p: 2 }}>
        <SectionTitle>Artifact Metadata</SectionTitle>
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 1.5,
            mb: 2,
            p: 1.5,
            borderRadius: 1,
            bgcolor: colors.bg.glass,
            border: `1px solid ${colors.border.subtle}`,
          }}
        >
          <MetaField label="Artifact Name" value={artifact.name} />
          <MetaField label="Generated By" value={artifact.generatedBy} />
          <MetaField label="Model Used" value={artifact.modelUsed} />
          <MetaField label="Version" value={`v${artifact.version}`} />
          <MetaField label="Generated Date" value={artifact.generatedDate} />
          <Box>
            <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem', display: 'block' }}>
              Approval Status
            </Typography>
            <Chip
              label={artifact.approvalStatus}
              size="small"
              sx={{
                mt: 0.25,
                height: 20,
                fontSize: '0.65rem',
                fontWeight: 700,
                bgcolor: `${statusColor}22`,
                color: statusColor,
                border: `1px solid ${statusColor}44`,
              }}
            />
          </Box>
        </Box>

        <SectionTitle>Generation History</SectionTitle>
        <Box sx={{ mb: 2 }}>
          {artifact.generationHistory.map((entry) => (
            <Box
              key={entry.version}
              sx={{
                p: 1,
                mb: 0.75,
                borderRadius: 1,
                bgcolor: colors.bg.glass,
                border: `1px solid ${colors.border.subtle}`,
                borderLeft: `3px solid ${colors.secondary}`,
              }}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="caption" sx={{ fontWeight: 700, fontSize: '0.7rem' }}>
                  v{entry.version}
                </Typography>
                <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem' }}>
                  {entry.generatedDate}
                </Typography>
              </Box>
              <Typography variant="body2" sx={{ fontSize: '0.75rem', mt: 0.25, lineHeight: 1.4 }}>
                {entry.changeSummary}
              </Typography>
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem', display: 'block', mt: 0.25 }}>
                {entry.generatedBy} · {entry.modelUsed}
              </Typography>
            </Box>
          ))}
        </Box>

        <SectionTitle>Preview</SectionTitle>
        <Box
          sx={{
            p: 1.5,
            borderRadius: 1,
            bgcolor: colors.bg.glass,
            border: `1px solid ${colors.border.subtle}`,
            maxHeight: 200,
            overflow: 'auto',
          }}
        >
          <Typography
            component="pre"
            sx={{
              fontFamily: 'monospace',
              fontSize: '0.7rem',
              lineHeight: 1.5,
              color: colors.text.secondary,
              whiteSpace: 'pre-wrap',
              m: 0,
            }}
          >
            {artifact.previewContent}
          </Typography>
        </Box>
      </DialogContent>
    </Dialog>
  );
}
