import { useState } from 'react';
import { Box, Chip, Typography } from '@mui/material';
import DescriptionIcon from '@mui/icons-material/Description';
import TableChartIcon from '@mui/icons-material/TableChart';
import { GlassCard } from '../common/GlassCard';
import { ModuleHeader } from '../common/ModuleHeader';
import { ArtifactDetailModal } from './ArtifactDetailModal';
import { generatedArtifacts } from '../../data/generatedArtifactsMock';
import type { ApprovalStatus, GeneratedArtifact } from '../../data/generatedArtifactsMock';
import { colors } from '../../theme/colors';

const statusColors: Record<ApprovalStatus, string> = {
  Approved: colors.success,
  'Pending Review': colors.warning,
  Draft: colors.info,
  Rejected: colors.critical,
};

function ArtifactRow({ artifact, onClick }: { artifact: GeneratedArtifact; onClick: () => void }) {
  const statusColor = statusColors[artifact.approvalStatus];
  const FileIcon = artifact.fileType === 'xlsx' ? TableChartIcon : DescriptionIcon;

  return (
    <Box
      role="button"
      tabIndex={0}
      onClick={onClick}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onClick();
        }
      }}
      sx={{
        display: 'flex',
        alignItems: 'center',
        gap: 2,
        py: 1,
        borderBottom: `1px solid ${colors.border.subtle}`,
        cursor: 'pointer',
        transition: 'background-color 0.15s',
        '&:hover': { bgcolor: colors.bg.glass },
        '&:focus-visible': { outline: `2px solid ${colors.primary}`, outlineOffset: -2 },
        flexWrap: 'wrap',
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, minWidth: 140 }}>
        <FileIcon sx={{ fontSize: 16, color: colors.primary }} />
        <Typography variant="caption" sx={{ fontWeight: 700 }}>{artifact.name}</Typography>
      </Box>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 100 }}>{artifact.generatedBy}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 60 }}>{artifact.modelUsed}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 40 }}>v{artifact.version}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ minWidth: 80 }}>{artifact.generatedDate}</Typography>
      <Chip
        label={artifact.approvalStatus}
        size="small"
        sx={{
          height: 20,
          fontSize: '0.65rem',
          fontWeight: 700,
          bgcolor: `${statusColor}22`,
          color: statusColor,
          border: `1px solid ${statusColor}44`,
          ml: 'auto',
        }}
      />
    </Box>
  );
}

export function GeneratedArtifactsPanel() {
  const [selected, setSelected] = useState<GeneratedArtifact | null>(null);

  return (
    <>
      <GlassCard sx={{ p: 2, mt: 1.5 }}>
        <ModuleHeader title="Generated Artifacts" subtitle="AI-generated requirement deliverables" />
        <Box
          sx={{
            display: { xs: 'none', md: 'flex' },
            gap: 2,
            py: 0.5,
            borderBottom: `1px solid ${colors.border.subtle}`,
            mb: 0.5,
          }}
        >
          {['Artifact', 'Generated By', 'Model', 'Version', 'Date', 'Status'].map((col) => (
            <Typography
              key={col}
              variant="caption"
              color="text.secondary"
              sx={{
                fontWeight: 700,
                fontSize: '0.65rem',
                textTransform: 'uppercase',
                letterSpacing: '0.04em',
                minWidth: col === 'Artifact' ? 140 : col === 'Status' ? undefined : col === 'Model' ? 60 : col === 'Version' ? 40 : 80,
                flex: col === 'Status' ? 0 : undefined,
                ml: col === 'Status' ? 'auto' : undefined,
              }}
            >
              {col}
            </Typography>
          ))}
        </Box>
        {generatedArtifacts.map((artifact) => (
          <ArtifactRow key={artifact.id} artifact={artifact} onClick={() => setSelected(artifact)} />
        ))}
      </GlassCard>

      <ArtifactDetailModal
        artifact={selected}
        open={selected !== null}
        onClose={() => setSelected(null)}
      />
    </>
  );
}
