"""UC18 - AI-assisted audit preparation

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc18]


@pytest.mark.workbook_id("UC18-FT001")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc18_ft001(case_runner):
    """UC18-FT001: Create audit preparation workspace/package"""
    case_runner("UC18-FT001")


@pytest.mark.workbook_id("UC18-FT002")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc18_ft002(case_runner):
    """UC18-FT002: Auto-assemble relevant evidence"""
    case_runner("UC18-FT002")


@pytest.mark.workbook_id("UC18-FT003")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc18_ft003(case_runner):
    """UC18-FT003: Verify evidence relevance and grounding"""
    case_runner("UC18-FT003")


@pytest.mark.workbook_id("UC18-FT004")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc18_ft004(case_runner):
    """UC18-FT004: Identify missing audit evidence"""
    case_runner("UC18-FT004")


@pytest.mark.workbook_id("UC18-FT005")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc18_ft005(case_runner):
    """UC18-FT005: Accept/reject AI suggestions"""
    case_runner("UC18-FT005")


@pytest.mark.workbook_id("UC18-FT006")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc18_ft006(case_runner):
    """UC18-FT006: Do not expose unauthorized evidence"""
    case_runner("UC18-FT006")


@pytest.mark.workbook_id("UC18-FT007")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc18_ft007(case_runner):
    """UC18-FT007: Handle AI service failure safely"""
    case_runner("UC18-FT007")


@pytest.mark.workbook_id("UC18-FT008")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc18_ft008(case_runner):
    """UC18-FT008: Export/finalize audit package"""
    case_runner("UC18-FT008")


@pytest.mark.workbook_id("UC18-FT009")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc18_ft009(case_runner):
    """UC18-FT009: Validate performance for AI-assisted audit preparation"""
    case_runner("UC18-FT009")


@pytest.mark.workbook_id("UC18-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc18_ft010(case_runner):
    """UC18-FT010: Validate notification mechanism for AI-assisted audit preparation"""
    case_runner("UC18-FT010")


@pytest.mark.workbook_id("UC18-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc18_ft011(case_runner):
    """UC18-FT011: Validate integration flow for AI-assisted audit preparation"""
    case_runner("UC18-FT011")


@pytest.mark.workbook_id("UC18-FT012")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc18_ft012(case_runner):
    """UC18-FT012: Validate data accuracy for AI-assisted audit preparation"""
    case_runner("UC18-FT012")


@pytest.mark.workbook_id("UC18-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc18_ft013(case_runner):
    """UC18-FT013: Validate retry and recovery for AI-assisted audit preparation"""
    case_runner("UC18-FT013")


@pytest.mark.workbook_id("UC18-FT014")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc18_ft014(case_runner):
    """UC18-FT014: Validate evidence integrity for AI-assisted audit preparation"""
    case_runner("UC18-FT014")


@pytest.mark.workbook_id("UC18-FT015")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc18_ft015(case_runner):
    """UC18-FT015: Validate concurrent user operations for AI-assisted audit preparation"""
    case_runner("UC18-FT015")


@pytest.mark.workbook_id("UC18-FT016")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc18_ft016(case_runner):
    """UC18-FT016: Validate dashboard/report visibility for AI-assisted audit preparation"""
    case_runner("UC18-FT016")


@pytest.mark.workbook_id("UC18-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc18_ft017(case_runner):
    """UC18-FT017: Validate retention and archival for AI-assisted audit preparation"""
    case_runner("UC18-FT017")
