"""UC14 - Automated control validation

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc14]


@pytest.mark.workbook_id("UC14-FT001")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft001(case_runner):
    """UC14-FT001: Create initial evidence version"""
    case_runner("UC14-FT001")


@pytest.mark.workbook_id("UC14-FT002")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft002(case_runner):
    """UC14-FT002: Create new version on update"""
    case_runner("UC14-FT002")


@pytest.mark.workbook_id("UC14-FT003")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft003(case_runner):
    """UC14-FT003: View version history"""
    case_runner("UC14-FT003")


@pytest.mark.workbook_id("UC14-FT004")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft004(case_runner):
    """UC14-FT004: Retrieve a historical version"""
    case_runner("UC14-FT004")


@pytest.mark.workbook_id("UC14-FT005")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft005(case_runner):
    """UC14-FT005: Apply retention policy"""
    case_runner("UC14-FT005")


@pytest.mark.workbook_id("UC14-FT006")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft006(case_runner):
    """UC14-FT006: Protect retained/audit evidence from unauthorized deletion"""
    case_runner("UC14-FT006")


@pytest.mark.workbook_id("UC14-FT007")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft007(case_runner):
    """UC14-FT007: Verify lifecycle status filters"""
    case_runner("UC14-FT007")


@pytest.mark.workbook_id("UC14-FT008")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.database
def test_uc14_ft008(case_runner):
    """UC14-FT008: Audit lifecycle actions"""
    case_runner("UC14-FT008")


@pytest.mark.workbook_id("UC14-FT009")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.negative
def test_uc14_ft009(case_runner):
    """UC14-FT009: Validate error handling for Automated control validation"""
    case_runner("UC14-FT009")


@pytest.mark.workbook_id("UC14-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc14_ft010(case_runner):
    """UC14-FT010: Validate notification mechanism for Automated control validation"""
    case_runner("UC14-FT010")


@pytest.mark.workbook_id("UC14-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc14_ft011(case_runner):
    """UC14-FT011: Validate integration flow for Automated control validation"""
    case_runner("UC14-FT011")


@pytest.mark.workbook_id("UC14-FT012")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc14_ft012(case_runner):
    """UC14-FT012: Validate retry and recovery for Automated control validation"""
    case_runner("UC14-FT012")


@pytest.mark.workbook_id("UC14-FT013")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
@pytest.mark.positive
def test_uc14_ft013(case_runner):
    """UC14-FT013: Validate compliance mapping for Automated control validation"""
    case_runner("UC14-FT013")


@pytest.mark.workbook_id("UC14-FT014")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc14_ft014(case_runner):
    """UC14-FT014: Validate concurrent user operations for Automated control validation"""
    case_runner("UC14-FT014")


@pytest.mark.workbook_id("UC14-FT015")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc14_ft015(case_runner):
    """UC14-FT015: Validate dashboard/report visibility for Automated control validation"""
    case_runner("UC14-FT015")
