"""UC20 - National compliance dashboard

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc20]


@pytest.mark.workbook_id("UC20-FT001")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft001(case_runner):
    """UC20-FT001: Load national compliance dashboard"""
    case_runner("UC20-FT001")


@pytest.mark.workbook_id("UC20-FT002")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft002(case_runner):
    """UC20-FT002: Aggregate across configured regions/entities"""
    case_runner("UC20-FT002")


@pytest.mark.workbook_id("UC20-FT003")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft003(case_runner):
    """UC20-FT003: Filter by region/entity/framework"""
    case_runner("UC20-FT003")


@pytest.mark.workbook_id("UC20-FT004")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft004(case_runner):
    """UC20-FT004: Drill national to regional/application detail"""
    case_runner("UC20-FT004")


@pytest.mark.workbook_id("UC20-FT005")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft005(case_runner):
    """UC20-FT005: Reconcile national totals"""
    case_runner("UC20-FT005")


@pytest.mark.workbook_id("UC20-FT006")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft006(case_runner):
    """UC20-FT006: Identify national exceptions/hotspots"""
    case_runner("UC20-FT006")


@pytest.mark.workbook_id("UC20-FT007")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft007(case_runner):
    """UC20-FT007: Verify national role/data segregation"""
    case_runner("UC20-FT007")


@pytest.mark.workbook_id("UC20-FT008")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc20_ft008(case_runner):
    """UC20-FT008: Refresh after regional update"""
    case_runner("UC20-FT008")


@pytest.mark.workbook_id("UC20-FT009")
@pytest.mark.priority_high
@pytest.mark.audit
@pytest.mark.database
@pytest.mark.positive
def test_uc20_ft009(case_runner):
    """UC20-FT009: Validate audit logging for National compliance dashboard"""
    case_runner("UC20-FT009")


@pytest.mark.workbook_id("UC20-FT010")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.negative
def test_uc20_ft010(case_runner):
    """UC20-FT010: Validate error handling for National compliance dashboard"""
    case_runner("UC20-FT010")


@pytest.mark.workbook_id("UC20-FT011")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc20_ft011(case_runner):
    """UC20-FT011: Validate notification mechanism for National compliance dashboard"""
    case_runner("UC20-FT011")


@pytest.mark.workbook_id("UC20-FT012")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc20_ft012(case_runner):
    """UC20-FT012: Validate integration flow for National compliance dashboard"""
    case_runner("UC20-FT012")


@pytest.mark.workbook_id("UC20-FT013")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc20_ft013(case_runner):
    """UC20-FT013: Validate data accuracy for National compliance dashboard"""
    case_runner("UC20-FT013")


@pytest.mark.workbook_id("UC20-FT014")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc20_ft014(case_runner):
    """UC20-FT014: Validate retry and recovery for National compliance dashboard"""
    case_runner("UC20-FT014")


@pytest.mark.workbook_id("UC20-FT015")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc20_ft015(case_runner):
    """UC20-FT015: Validate security controls for National compliance dashboard"""
    case_runner("UC20-FT015")


@pytest.mark.workbook_id("UC20-FT016")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc20_ft016(case_runner):
    """UC20-FT016: Validate evidence integrity for National compliance dashboard"""
    case_runner("UC20-FT016")


@pytest.mark.workbook_id("UC20-FT017")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc20_ft017(case_runner):
    """UC20-FT017: Validate concurrent user operations for National compliance dashboard"""
    case_runner("UC20-FT017")


@pytest.mark.workbook_id("UC20-FT018")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc20_ft018(case_runner):
    """UC20-FT018: Validate retention and archival for National compliance dashboard"""
    case_runner("UC20-FT018")
