"""UC10 - Leadership compliance dashboards

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc10]


@pytest.mark.workbook_id("UC10-FT001")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft001(case_runner):
    """UC10-FT001: Generate evidence summary"""
    case_runner("UC10-FT001")


@pytest.mark.workbook_id("UC10-FT002")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft002(case_runner):
    """UC10-FT002: Ground summary in source evidence"""
    case_runner("UC10-FT002")


@pytest.mark.workbook_id("UC10-FT003")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc10_ft003(case_runner):
    """UC10-FT003: Handle unsupported/empty content"""
    case_runner("UC10-FT003")


@pytest.mark.workbook_id("UC10-FT004")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft004(case_runner):
    """UC10-FT004: Regenerate summary after new version"""
    case_runner("UC10-FT004")


@pytest.mark.workbook_id("UC10-FT005")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft005(case_runner):
    """UC10-FT005: Display AI provenance/context"""
    case_runner("UC10-FT005")


@pytest.mark.workbook_id("UC10-FT006")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc10_ft006(case_runner):
    """UC10-FT006: Respect access control"""
    case_runner("UC10-FT006")


@pytest.mark.workbook_id("UC10-FT007")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft007(case_runner):
    """UC10-FT007: Handle AI service failure"""
    case_runner("UC10-FT007")


@pytest.mark.workbook_id("UC10-FT008")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc10_ft008(case_runner):
    """UC10-FT008: Audit summary generation"""
    case_runner("UC10-FT008")


@pytest.mark.workbook_id("UC10-FT009")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc10_ft009(case_runner):
    """UC10-FT009: Validate performance for Leadership compliance dashboards"""
    case_runner("UC10-FT009")


@pytest.mark.workbook_id("UC10-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc10_ft010(case_runner):
    """UC10-FT010: Validate notification mechanism for Leadership compliance dashboards"""
    case_runner("UC10-FT010")


@pytest.mark.workbook_id("UC10-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc10_ft011(case_runner):
    """UC10-FT011: Validate integration flow for Leadership compliance dashboards"""
    case_runner("UC10-FT011")


@pytest.mark.workbook_id("UC10-FT012")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc10_ft012(case_runner):
    """UC10-FT012: Validate data accuracy for Leadership compliance dashboards"""
    case_runner("UC10-FT012")


@pytest.mark.workbook_id("UC10-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc10_ft013(case_runner):
    """UC10-FT013: Validate retry and recovery for Leadership compliance dashboards"""
    case_runner("UC10-FT013")


@pytest.mark.workbook_id("UC10-FT014")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc10_ft014(case_runner):
    """UC10-FT014: Validate security controls for Leadership compliance dashboards"""
    case_runner("UC10-FT014")


@pytest.mark.workbook_id("UC10-FT015")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc10_ft015(case_runner):
    """UC10-FT015: Validate evidence integrity for Leadership compliance dashboards"""
    case_runner("UC10-FT015")


@pytest.mark.workbook_id("UC10-FT016")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc10_ft016(case_runner):
    """UC10-FT016: Validate concurrent user operations for Leadership compliance dashboards"""
    case_runner("UC10-FT016")


@pytest.mark.workbook_id("UC10-FT017")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc10_ft017(case_runner):
    """UC10-FT017: Validate dashboard/report visibility for Leadership compliance dashboards"""
    case_runner("UC10-FT017")


@pytest.mark.workbook_id("UC10-FT018")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc10_ft018(case_runner):
    """UC10-FT018: Validate retention and archival for Leadership compliance dashboards"""
    case_runner("UC10-FT018")
