"""Generate docs/functional-test-traceability.yaml: Workbook Test ID -> automation test -> framework capability -> ECS component -> data -> expected.

Imports only the use-case modules (pure registration; no ECS call, no test execution).
Usage (repo root):  python tests/functional/tools/build_traceability.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

FUNC = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(FUNC.parent))
sys.path.insert(0, str(FUNC.parents[1]))

from functional.framework import registry  # noqa: E402
from functional.framework.spec import META  # noqa: E402
from functional.usecases import ensure_loaded  # noqa: E402

OUT = FUNC.parents[1] / "docs" / "functional-test-traceability.yaml"


def build() -> dict:
    ensure_loaded()
    entries = []
    missing = []
    for tid, t in registry.all_tests().items():
        m = META.get(tid)
        if m is None:
            missing.append(tid)
            continue
        entries.append({
            "workbook_test_id": tid,
            "use_case": f"{t.uc} - {t.uc_name}",
            "test_name": t.name,
            "priority": t.priority,
            "test_type": t.type,
            "automation_test": f"tests/functional/usecases/{t.uc.lower()}/test_{t.uc.lower()}.py::test_{tid.lower().replace('-', '_')}",
            "orchestration": f"tests/functional/usecases/{t.uc.lower()}/orchestration.py",
            "kind": m.kind,
            "framework": m.framework,
            "capability": m.capability,
            "ecs_component": m.component,
            "test_data": m.data,
            "preconditions": t.preconditions,
            "steps": t.steps,
            "expected": t.expected,
            "markers": list(t.markers),
        })
    if missing:
        raise SystemExit(f"unmapped workbook tests: {missing}")
    return {"source_workbook": registry.load_raw()["source_workbook"], "total": len(entries), "tests": entries}


if __name__ == "__main__":
    doc = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# GENERATED by tests/functional/tools/build_traceability.py - do not edit by hand.\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=140)
    print(f"wrote {OUT} - {doc['total']} workbook tests mapped")
