"""Generate usecases/ucNN/test_ucNN.py - one pytest function per workbook Functional Test ID (exact IDs, no renumbering).

Each generated function is a thin binding: ``case_runner("<ID>")`` -> usecases/ucNN/orchestration.py -> reusable helpers.
Usage (repo root):  python tests/functional/tools/generate_tests.py
"""

from __future__ import annotations

import sys
from pathlib import Path

FUNC = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(FUNC.parent))
sys.path.insert(0, str(FUNC.parents[1]))

from functional.framework import registry  # noqa: E402

HEADER = '''"""{uc} - {name}

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.{ucm}]
'''

FUNC_TMPL = '''

{marks}
def test_{fn}(case_runner):
    """{tid}: {tname}"""
    case_runner("{tid}")
'''


def main() -> None:
    total = 0
    for uc, name in registry.use_cases().items():
        lines = [HEADER.format(uc=uc, name=name, ucm=uc.lower())]
        for t in registry.tests_for(uc):
            extra = [m for m in t.markers if m not in ("functional", uc.lower())]
            marks = [f'@pytest.mark.workbook_id("{t.id}")', f"@pytest.mark.priority_{t.priority.lower()}"]
            marks += [f"@pytest.mark.{m}" for m in extra]
            lines.append(FUNC_TMPL.format(marks="\n".join(marks), fn=t.id.lower().replace("-", "_"), tid=t.id,
                                          tname=t.name.replace('"', "'")))
            total += 1
        out = FUNC / "usecases" / uc.lower() / f"test_{uc.lower()}.py"
        out.write_text("".join(lines), encoding="utf-8")
    print(f"generated {len(registry.use_cases())} files, {total} test functions")


if __name__ == "__main__":
    main()
