"""UC17 - Automated regulatory reporting

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc17]


@pytest.mark.workbook_id("UC17-FT001")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft001(case_runner):
    """UC17-FT001: Generate regulatory report"""
    case_runner("UC17-FT001")


@pytest.mark.workbook_id("UC17-FT002")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft002(case_runner):
    """UC17-FT002: Populate report from ECS evidence/control data"""
    case_runner("UC17-FT002")


@pytest.mark.workbook_id("UC17-FT003")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft003(case_runner):
    """UC17-FT003: Include evidence traceability"""
    case_runner("UC17-FT003")


@pytest.mark.workbook_id("UC17-FT004")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft004(case_runner):
    """UC17-FT004: Apply reporting period correctly"""
    case_runner("UC17-FT004")


@pytest.mark.workbook_id("UC17-FT005")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft005(case_runner):
    """UC17-FT005: Handle incomplete reporting data"""
    case_runner("UC17-FT005")


@pytest.mark.workbook_id("UC17-FT006")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft006(case_runner):
    """UC17-FT006: Reproduce report deterministically"""
    case_runner("UC17-FT006")


@pytest.mark.workbook_id("UC17-FT007")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft007(case_runner):
    """UC17-FT007: Export report"""
    case_runner("UC17-FT007")


@pytest.mark.workbook_id("UC17-FT008")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc17_ft008(case_runner):
    """UC17-FT008: Audit report generation"""
    case_runner("UC17-FT008")


@pytest.mark.workbook_id("UC17-FT009")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc17_ft009(case_runner):
    """UC17-FT009: Validate role-based access for Automated regulatory reporting"""
    case_runner("UC17-FT009")


@pytest.mark.workbook_id("UC17-FT010")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc17_ft010(case_runner):
    """UC17-FT010: Validate performance for Automated regulatory reporting"""
    case_runner("UC17-FT010")


@pytest.mark.workbook_id("UC17-FT011")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc17_ft011(case_runner):
    """UC17-FT011: Validate notification mechanism for Automated regulatory reporting"""
    case_runner("UC17-FT011")


@pytest.mark.workbook_id("UC17-FT012")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc17_ft012(case_runner):
    """UC17-FT012: Validate integration flow for Automated regulatory reporting"""
    case_runner("UC17-FT012")


@pytest.mark.workbook_id("UC17-FT013")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc17_ft013(case_runner):
    """UC17-FT013: Validate data accuracy for Automated regulatory reporting"""
    case_runner("UC17-FT013")


@pytest.mark.workbook_id("UC17-FT014")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc17_ft014(case_runner):
    """UC17-FT014: Validate retry and recovery for Automated regulatory reporting"""
    case_runner("UC17-FT014")


@pytest.mark.workbook_id("UC17-FT015")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc17_ft015(case_runner):
    """UC17-FT015: Validate security controls for Automated regulatory reporting"""
    case_runner("UC17-FT015")


@pytest.mark.workbook_id("UC17-FT016")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc17_ft016(case_runner):
    """UC17-FT016: Validate evidence integrity for Automated regulatory reporting"""
    case_runner("UC17-FT016")


@pytest.mark.workbook_id("UC17-FT017")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc17_ft017(case_runner):
    """UC17-FT017: Validate concurrent user operations for Automated regulatory reporting"""
    case_runner("UC17-FT017")


@pytest.mark.workbook_id("UC17-FT018")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc17_ft018(case_runner):
    """UC17-FT018: Validate retention and archival for Automated regulatory reporting"""
    case_runner("UC17-FT018")
