import { Box, Chip, Typography } from '@mui/material';
import { GlassCard } from '../common/GlassCard';
import { ModuleHeader } from '../common/ModuleHeader';
import { colors } from '../../theme/colors';
import type { GenerationRun, GenerationRunStatus } from '../../types/artifacts';

const statusColors: Record<GenerationRunStatus, string> = {
  Completed: colors.success,
  'In Progress': colors.warning,
  Failed: colors.critical,
};

interface GenerationRunHistoryPanelProps {
  runs: GenerationRun[];
}

export function GenerationRunHistoryPanel({ runs }: GenerationRunHistoryPanelProps) {
  if (runs.length === 0) return null;

  return (
    <GlassCard sx={{ p: 2, mt: 1.5 }}>
      <ModuleHeader title="Generation History" subtitle="Workflow run audit trail" />
      <Box
        sx={{
          display: { xs: 'none', md: 'flex' },
          gap: 2,
          py: 0.5,
          borderBottom: `1px solid ${colors.border.subtle}`,
          mb: 0.5,
        }}
      >
        {['Run ID', 'Timestamp', 'Generated By', 'Status'].map((col) => (
          <Typography
            key={col}
            variant="caption"
            color="text.secondary"
            sx={{
              fontWeight: 700,
              fontSize: '0.65rem',
              textTransform: 'uppercase',
              letterSpacing: '0.04em',
              minWidth: col === 'Run ID' ? 120 : col === 'Timestamp' ? 160 : col === 'Generated By' ? 120 : undefined,
              ml: col === 'Status' ? 'auto' : undefined,
            }}
          >
            {col}
          </Typography>
        ))}
      </Box>
      {runs.map((run) => {
        const statusColor = statusColors[run.status];
        return (
          <Box
            key={run.runId}
            sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 2,
              py: 1,
              borderBottom: `1px solid ${colors.border.subtle}`,
              flexWrap: 'wrap',
            }}
          >
            <Typography variant="caption" sx={{ fontWeight: 700, minWidth: 120, fontFamily: 'monospace', fontSize: '0.7rem' }}>
              {run.runId}
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ minWidth: 160 }}>
              {run.timestamp}
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ minWidth: 120 }}>
              {run.generatedBy}
            </Typography>
            <Chip
              label={run.status}
              size="small"
              sx={{
                height: 20,
                fontSize: '0.65rem',
                fontWeight: 700,
                bgcolor: `${statusColor}22`,
                color: statusColor,
                border: `1px solid ${statusColor}44`,
                ml: 'auto',
              }}
            />
          </Box>
        );
      })}
    </GlassCard>
  );
}
