"""UC09 - Natural language audit queries (prebuilt/NLQ)

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc09]


@pytest.mark.workbook_id("UC09-FT001")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc09_ft001(case_runner):
    """UC09-FT001: Find similar evidence"""
    case_runner("UC09-FT001")


@pytest.mark.workbook_id("UC09-FT002")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc09_ft002(case_runner):
    """UC09-FT002: Do not suggest unrelated evidence"""
    case_runner("UC09-FT002")


@pytest.mark.workbook_id("UC09-FT003")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc09_ft003(case_runner):
    """UC09-FT003: Display similarity context"""
    case_runner("UC09-FT003")


@pytest.mark.workbook_id("UC09-FT004")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc09_ft004(case_runner):
    """UC09-FT004: Reuse approved evidence"""
    case_runner("UC09-FT004")


@pytest.mark.workbook_id("UC09-FT005")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc09_ft005(case_runner):
    """UC09-FT005: Preserve original ownership/traceability"""
    case_runner("UC09-FT005")


@pytest.mark.workbook_id("UC09-FT006")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc09_ft006(case_runner):
    """UC09-FT006: Respect scope/security on reuse"""
    case_runner("UC09-FT006")


@pytest.mark.workbook_id("UC09-FT007")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc09_ft007(case_runner):
    """UC09-FT007: Handle no-similarity result"""
    case_runner("UC09-FT007")


@pytest.mark.workbook_id("UC09-FT008")
@pytest.mark.priority_high
@pytest.mark.audit
@pytest.mark.database
def test_uc09_ft008(case_runner):
    """UC09-FT008: Audit reuse decision"""
    case_runner("UC09-FT008")


@pytest.mark.workbook_id("UC09-FT009")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc09_ft009(case_runner):
    """UC09-FT009: Validate notification mechanism for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT009")


@pytest.mark.workbook_id("UC09-FT010")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc09_ft010(case_runner):
    """UC09-FT010: Validate integration flow for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT010")


@pytest.mark.workbook_id("UC09-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc09_ft011(case_runner):
    """UC09-FT011: Validate retry and recovery for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT011")


@pytest.mark.workbook_id("UC09-FT012")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc09_ft012(case_runner):
    """UC09-FT012: Validate evidence integrity for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT012")


@pytest.mark.workbook_id("UC09-FT013")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc09_ft013(case_runner):
    """UC09-FT013: Validate concurrent user operations for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT013")


@pytest.mark.workbook_id("UC09-FT014")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc09_ft014(case_runner):
    """UC09-FT014: Validate dashboard/report visibility for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT014")


@pytest.mark.workbook_id("UC09-FT015")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc09_ft015(case_runner):
    """UC09-FT015: Validate retention and archival for Natural language audit queries (prebuilt/NLQ)"""
    case_runner("UC09-FT015")
