"""UC12 - Evidence lifecycle management

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc12]


@pytest.mark.workbook_id("UC12-FT001")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc12_ft001(case_runner):
    """UC12-FT001: Load leadership compliance summary"""
    case_runner("UC12-FT001")


@pytest.mark.workbook_id("UC12-FT002")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc12_ft002(case_runner):
    """UC12-FT002: Filter by business/application/framework"""
    case_runner("UC12-FT002")


@pytest.mark.workbook_id("UC12-FT003")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc12_ft003(case_runner):
    """UC12-FT003: Drill down from KPI to detail"""
    case_runner("UC12-FT003")


@pytest.mark.workbook_id("UC12-FT004")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc12_ft004(case_runner):
    """UC12-FT004: Reconcile dashboard with source data"""
    case_runner("UC12-FT004")


@pytest.mark.workbook_id("UC12-FT005")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc12_ft005(case_runner):
    """UC12-FT005: Highlight incomplete/exception areas"""
    case_runner("UC12-FT005")


@pytest.mark.workbook_id("UC12-FT006")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc12_ft006(case_runner):
    """UC12-FT006: Verify role-based visibility"""
    case_runner("UC12-FT006")


@pytest.mark.workbook_id("UC12-FT007")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc12_ft007(case_runner):
    """UC12-FT007: Refresh after evidence/control update"""
    case_runner("UC12-FT007")


@pytest.mark.workbook_id("UC12-FT008")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc12_ft008(case_runner):
    """UC12-FT008: Export/view report if enabled"""
    case_runner("UC12-FT008")


@pytest.mark.workbook_id("UC12-FT009")
@pytest.mark.priority_high
@pytest.mark.audit
@pytest.mark.database
@pytest.mark.positive
def test_uc12_ft009(case_runner):
    """UC12-FT009: Validate audit logging for Evidence lifecycle management"""
    case_runner("UC12-FT009")


@pytest.mark.workbook_id("UC12-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc12_ft010(case_runner):
    """UC12-FT010: Validate notification mechanism for Evidence lifecycle management"""
    case_runner("UC12-FT010")


@pytest.mark.workbook_id("UC12-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc12_ft011(case_runner):
    """UC12-FT011: Validate integration flow for Evidence lifecycle management"""
    case_runner("UC12-FT011")


@pytest.mark.workbook_id("UC12-FT012")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc12_ft012(case_runner):
    """UC12-FT012: Validate data accuracy for Evidence lifecycle management"""
    case_runner("UC12-FT012")


@pytest.mark.workbook_id("UC12-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc12_ft013(case_runner):
    """UC12-FT013: Validate retry and recovery for Evidence lifecycle management"""
    case_runner("UC12-FT013")


@pytest.mark.workbook_id("UC12-FT014")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc12_ft014(case_runner):
    """UC12-FT014: Validate security controls for Evidence lifecycle management"""
    case_runner("UC12-FT014")


@pytest.mark.workbook_id("UC12-FT015")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc12_ft015(case_runner):
    """UC12-FT015: Validate evidence integrity for Evidence lifecycle management"""
    case_runner("UC12-FT015")


@pytest.mark.workbook_id("UC12-FT016")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc12_ft016(case_runner):
    """UC12-FT016: Validate concurrent user operations for Evidence lifecycle management"""
    case_runner("UC12-FT016")


@pytest.mark.workbook_id("UC12-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc12_ft017(case_runner):
    """UC12-FT017: Validate retention and archival for Evidence lifecycle management"""
    case_runner("UC12-FT017")
