"""UC08 - AI-generated evidence summaries

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc08]


@pytest.mark.workbook_id("UC08-FT001")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft001(case_runner):
    """UC08-FT001: Detect missing required evidence"""
    case_runner("UC08-FT001")


@pytest.mark.workbook_id("UC08-FT002")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft002(case_runner):
    """UC08-FT002: Mark complete control correctly"""
    case_runner("UC08-FT002")


@pytest.mark.workbook_id("UC08-FT003")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft003(case_runner):
    """UC08-FT003: Recalculate after evidence upload"""
    case_runner("UC08-FT003")


@pytest.mark.workbook_id("UC08-FT004")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc08_ft004(case_runner):
    """UC08-FT004: Respect application/environment scope"""
    case_runner("UC08-FT004")


@pytest.mark.workbook_id("UC08-FT005")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft005(case_runner):
    """UC08-FT005: Show completeness reason/detail"""
    case_runner("UC08-FT005")


@pytest.mark.workbook_id("UC08-FT006")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft006(case_runner):
    """UC08-FT006: Handle expired/invalid evidence"""
    case_runner("UC08-FT006")


@pytest.mark.workbook_id("UC08-FT007")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc08_ft007(case_runner):
    """UC08-FT007: Dashboard completeness reconciliation"""
    case_runner("UC08-FT007")


@pytest.mark.workbook_id("UC08-FT008")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc08_ft008(case_runner):
    """UC08-FT008: Audit completeness evaluation"""
    case_runner("UC08-FT008")


@pytest.mark.workbook_id("UC08-FT009")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc08_ft009(case_runner):
    """UC08-FT009: Validate role-based access for AI-generated evidence summaries"""
    case_runner("UC08-FT009")


@pytest.mark.workbook_id("UC08-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc08_ft010(case_runner):
    """UC08-FT010: Validate notification mechanism for AI-generated evidence summaries"""
    case_runner("UC08-FT010")


@pytest.mark.workbook_id("UC08-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc08_ft011(case_runner):
    """UC08-FT011: Validate integration flow for AI-generated evidence summaries"""
    case_runner("UC08-FT011")


@pytest.mark.workbook_id("UC08-FT012")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc08_ft012(case_runner):
    """UC08-FT012: Validate data accuracy for AI-generated evidence summaries"""
    case_runner("UC08-FT012")


@pytest.mark.workbook_id("UC08-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc08_ft013(case_runner):
    """UC08-FT013: Validate retry and recovery for AI-generated evidence summaries"""
    case_runner("UC08-FT013")


@pytest.mark.workbook_id("UC08-FT014")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc08_ft014(case_runner):
    """UC08-FT014: Validate security controls for AI-generated evidence summaries"""
    case_runner("UC08-FT014")


@pytest.mark.workbook_id("UC08-FT015")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc08_ft015(case_runner):
    """UC08-FT015: Validate evidence integrity for AI-generated evidence summaries"""
    case_runner("UC08-FT015")


@pytest.mark.workbook_id("UC08-FT016")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc08_ft016(case_runner):
    """UC08-FT016: Validate concurrent user operations for AI-generated evidence summaries"""
    case_runner("UC08-FT016")


@pytest.mark.workbook_id("UC08-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc08_ft017(case_runner):
    """UC08-FT017: Validate retention and archival for AI-generated evidence summaries"""
    case_runner("UC08-FT017")
