"""UC11 - Multi-application onboarding

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc11]


@pytest.mark.workbook_id("UC11-FT001")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc11_ft001(case_runner):
    """UC11-FT001: Ask natural-language evidence question"""
    case_runner("UC11-FT001")


@pytest.mark.workbook_id("UC11-FT002")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc11_ft002(case_runner):
    """UC11-FT002: Verify citation/evidence grounding"""
    case_runner("UC11-FT002")


@pytest.mark.workbook_id("UC11-FT003")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc11_ft003(case_runner):
    """UC11-FT003: Apply application/framework context"""
    case_runner("UC11-FT003")


@pytest.mark.workbook_id("UC11-FT004")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc11_ft004(case_runner):
    """UC11-FT004: Handle no-answer scenario"""
    case_runner("UC11-FT004")


@pytest.mark.workbook_id("UC11-FT005")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc11_ft005(case_runner):
    """UC11-FT005: Follow-up query retains intended context"""
    case_runner("UC11-FT005")


@pytest.mark.workbook_id("UC11-FT006")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
def test_uc11_ft006(case_runner):
    """UC11-FT006: Respect evidence permissions"""
    case_runner("UC11-FT006")


@pytest.mark.workbook_id("UC11-FT007")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc11_ft007(case_runner):
    """UC11-FT007: Handle AI/vector service failure"""
    case_runner("UC11-FT007")


@pytest.mark.workbook_id("UC11-FT008")
@pytest.mark.priority_high
@pytest.mark.ai
@pytest.mark.api
def test_uc11_ft008(case_runner):
    """UC11-FT008: Audit natural-language query"""
    case_runner("UC11-FT008")


@pytest.mark.workbook_id("UC11-FT009")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc11_ft009(case_runner):
    """UC11-FT009: Validate performance for Multi-application onboarding"""
    case_runner("UC11-FT009")


@pytest.mark.workbook_id("UC11-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc11_ft010(case_runner):
    """UC11-FT010: Validate notification mechanism for Multi-application onboarding"""
    case_runner("UC11-FT010")


@pytest.mark.workbook_id("UC11-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc11_ft011(case_runner):
    """UC11-FT011: Validate integration flow for Multi-application onboarding"""
    case_runner("UC11-FT011")


@pytest.mark.workbook_id("UC11-FT012")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc11_ft012(case_runner):
    """UC11-FT012: Validate evidence integrity for Multi-application onboarding"""
    case_runner("UC11-FT012")


@pytest.mark.workbook_id("UC11-FT013")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc11_ft013(case_runner):
    """UC11-FT013: Validate concurrent user operations for Multi-application onboarding"""
    case_runner("UC11-FT013")


@pytest.mark.workbook_id("UC11-FT014")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc11_ft014(case_runner):
    """UC11-FT014: Validate dashboard/report visibility for Multi-application onboarding"""
    case_runner("UC11-FT014")


@pytest.mark.workbook_id("UC11-FT015")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc11_ft015(case_runner):
    """UC11-FT015: Validate retention and archival for Multi-application onboarding"""
    case_runner("UC11-FT015")
