"""UC01 - Automated scheduled evidence pull

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc01]


@pytest.mark.workbook_id("UC01-FT001")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft001(case_runner):
    """UC01-FT001: Create scheduled evidence collection job"""
    case_runner("UC01-FT001")


@pytest.mark.workbook_id("UC01-FT002")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft002(case_runner):
    """UC01-FT002: Execute scheduled pull successfully"""
    case_runner("UC01-FT002")


@pytest.mark.workbook_id("UC01-FT003")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc01_ft003(case_runner):
    """UC01-FT003: Persist collected evidence"""
    case_runner("UC01-FT003")


@pytest.mark.workbook_id("UC01-FT004")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft004(case_runner):
    """UC01-FT004: Prevent duplicate scheduled ingestion"""
    case_runner("UC01-FT004")


@pytest.mark.workbook_id("UC01-FT005")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft005(case_runner):
    """UC01-FT005: Handle source authentication failure"""
    case_runner("UC01-FT005")


@pytest.mark.workbook_id("UC01-FT006")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft006(case_runner):
    """UC01-FT006: Recover on next scheduled run"""
    case_runner("UC01-FT006")


@pytest.mark.workbook_id("UC01-FT007")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft007(case_runner):
    """UC01-FT007: Verify scheduler audit trail"""
    case_runner("UC01-FT007")


@pytest.mark.workbook_id("UC01-FT008")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc01_ft008(case_runner):
    """UC01-FT008: Verify restart durability"""
    case_runner("UC01-FT008")


@pytest.mark.workbook_id("UC01-FT009")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc01_ft009(case_runner):
    """UC01-FT009: Validate role-based access for Automated scheduled evidence pull"""
    case_runner("UC01-FT009")


@pytest.mark.workbook_id("UC01-FT010")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc01_ft010(case_runner):
    """UC01-FT010: Validate performance for Automated scheduled evidence pull"""
    case_runner("UC01-FT010")


@pytest.mark.workbook_id("UC01-FT011")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc01_ft011(case_runner):
    """UC01-FT011: Validate notification mechanism for Automated scheduled evidence pull"""
    case_runner("UC01-FT011")


@pytest.mark.workbook_id("UC01-FT012")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc01_ft012(case_runner):
    """UC01-FT012: Validate security controls for Automated scheduled evidence pull"""
    case_runner("UC01-FT012")


@pytest.mark.workbook_id("UC01-FT013")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc01_ft013(case_runner):
    """UC01-FT013: Validate evidence integrity for Automated scheduled evidence pull"""
    case_runner("UC01-FT013")


@pytest.mark.workbook_id("UC01-FT014")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
@pytest.mark.positive
def test_uc01_ft014(case_runner):
    """UC01-FT014: Validate compliance mapping for Automated scheduled evidence pull"""
    case_runner("UC01-FT014")


@pytest.mark.workbook_id("UC01-FT015")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc01_ft015(case_runner):
    """UC01-FT015: Validate concurrent user operations for Automated scheduled evidence pull"""
    case_runner("UC01-FT015")


@pytest.mark.workbook_id("UC01-FT016")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc01_ft016(case_runner):
    """UC01-FT016: Validate dashboard/report visibility for Automated scheduled evidence pull"""
    case_runner("UC01-FT016")


@pytest.mark.workbook_id("UC01-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc01_ft017(case_runner):
    """UC01-FT017: Validate retention and archival for Automated scheduled evidence pull"""
    case_runner("UC01-FT017")
