"""UC15 - SharePoint, SNOW integration

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc15]


@pytest.mark.workbook_id("UC15-FT001")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft001(case_runner):
    """UC15-FT001: Compare two applications"""
    case_runner("UC15-FT001")


@pytest.mark.workbook_id("UC15-FT002")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft002(case_runner):
    """UC15-FT002: Compare control/framework coverage"""
    case_runner("UC15-FT002")


@pytest.mark.workbook_id("UC15-FT003")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft003(case_runner):
    """UC15-FT003: Identify gaps between applications"""
    case_runner("UC15-FT003")


@pytest.mark.workbook_id("UC15-FT004")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft004(case_runner):
    """UC15-FT004: Drill down comparison differences"""
    case_runner("UC15-FT004")


@pytest.mark.workbook_id("UC15-FT005")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft005(case_runner):
    """UC15-FT005: Exclude out-of-scope controls"""
    case_runner("UC15-FT005")


@pytest.mark.workbook_id("UC15-FT006")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft006(case_runner):
    """UC15-FT006: Verify comparison calculation accuracy"""
    case_runner("UC15-FT006")


@pytest.mark.workbook_id("UC15-FT007")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
def test_uc15_ft007(case_runner):
    """UC15-FT007: Respect cross-application permissions"""
    case_runner("UC15-FT007")


@pytest.mark.workbook_id("UC15-FT008")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc15_ft008(case_runner):
    """UC15-FT008: Export comparison if enabled"""
    case_runner("UC15-FT008")


@pytest.mark.workbook_id("UC15-FT009")
@pytest.mark.priority_high
@pytest.mark.audit
@pytest.mark.database
@pytest.mark.positive
def test_uc15_ft009(case_runner):
    """UC15-FT009: Validate audit logging for SharePoint, SNOW integration"""
    case_runner("UC15-FT009")


@pytest.mark.workbook_id("UC15-FT010")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc15_ft010(case_runner):
    """UC15-FT010: Validate performance for SharePoint, SNOW integration"""
    case_runner("UC15-FT010")


@pytest.mark.workbook_id("UC15-FT011")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc15_ft011(case_runner):
    """UC15-FT011: Validate notification mechanism for SharePoint, SNOW integration"""
    case_runner("UC15-FT011")


@pytest.mark.workbook_id("UC15-FT012")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.api
@pytest.mark.positive
def test_uc15_ft012(case_runner):
    """UC15-FT012: Validate integration flow for SharePoint, SNOW integration"""
    case_runner("UC15-FT012")


@pytest.mark.workbook_id("UC15-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc15_ft013(case_runner):
    """UC15-FT013: Validate retry and recovery for SharePoint, SNOW integration"""
    case_runner("UC15-FT013")


@pytest.mark.workbook_id("UC15-FT014")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc15_ft014(case_runner):
    """UC15-FT014: Validate evidence integrity for SharePoint, SNOW integration"""
    case_runner("UC15-FT014")


@pytest.mark.workbook_id("UC15-FT015")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc15_ft015(case_runner):
    """UC15-FT015: Validate concurrent user operations for SharePoint, SNOW integration"""
    case_runner("UC15-FT015")


@pytest.mark.workbook_id("UC15-FT016")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc15_ft016(case_runner):
    """UC15-FT016: Validate retention and archival for SharePoint, SNOW integration"""
    case_runner("UC15-FT016")
