#!/usr/bin/env python3
"""ECS configuration developer/ops toolbox.

One CLI for the deployment-configuration workflow — validate, inspect, compare and
scaffold ECS environment configuration. Read-only and secret-safe (secrets are
shown as SET / MISSING, never their value).

Subcommands
-----------
  validate-config [ENV] [--check-secrets]   Validate an env (default: active/ECS_ENV)
  validate-all [--check-secrets]            Validate every env with a YAML file
  validate-uat / validate-prod / validate-dr [--check-secrets]
                                            Shorthands for the strict deploy tiers
  show-current-config [ENV] [--json]        Print the resolved deployment profile
  compare-envs ENV_A ENV_B [--json]         Diff two environments field-by-field
  generate-env-template ENV                 Emit a .env template for an environment

Examples
--------
  python scripts/config_tools.py validate-all
  python scripts/config_tools.py validate-prod --check-secrets
  python scripts/config_tools.py show-current-config prod
  python scripts/config_tools.py compare-envs local prod
  python scripts/config_tools.py generate-env-template dr > .env.dr
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _cmd_validate(env: str | None, *, check_secrets: bool, all_envs: bool = False) -> int:
    from config.config_validation import _format, validate_all, validate_environment

    if all_envs:
        reports = validate_all(check_secrets=check_secrets)
        print("\n".join(_format(r) for r in reports.values()))
        return 0 if all(r.ok for r in reports.values()) else 1
    rep = validate_environment(env, check_secrets=check_secrets)
    print(_format(rep))
    return 0 if rep.ok else 1


def _cmd_show(env: str | None, *, as_json: bool) -> int:
    from config.deployment_profiles import _render, build_profile

    profile = build_profile(env)
    print(json.dumps(profile, indent=2, default=str) if as_json else _render(profile))
    return 0


def _cmd_compare(env_a: str, env_b: str, *, as_json: bool) -> int:
    from config.deployment_profiles import diff_profiles

    d = diff_profiles(env_a, env_b)
    if as_json:
        print(json.dumps(d, indent=2, default=str))
        return 0
    print(f"Config differences: {env_a} vs {env_b} ({d['diff_count']} fields)")
    for path, vals in sorted(d["differences"].items()):
        print(f"  {path}:")
        print(f"    {env_a}: {vals[env_a]}")
        print(f"    {env_b}: {vals[env_b]}")
    return 0


def _cmd_generate_template(env: str) -> int:
    """Emit a .env template listing every ${VAR} the env's config references."""
    import re

    from ecs_platform.config.loader import config_dir

    placeholder = re.compile(r"\$\{([A-Z0-9_]+)(?::-([^}]*))?\}")
    seen: dict[str, str] = {}
    for name in ("environments/_base", f"environments/{env}"):
        path = config_dir() / f"{name}.yaml"
        if not path.is_file():
            continue
        for m in placeholder.finditer(path.read_text(encoding="utf-8")):
            var, default = m.group(1), m.group(2) or ""
            # Do not print secret defaults; blank them for the template.
            seen.setdefault(var, default)
    print(f"# ECS .env template for environment: {env}")
    print(f"# Generated by scripts/config_tools.py — fill in real values, keep secrets out of git.")
    print(f"ECS_ENV={env}")
    for var in sorted(seen):
        is_secret = any(s in var for s in ("PASSWORD", "SECRET", "TOKEN", "KEY", "CLIENT_SECRET"))
        default = "" if is_secret else seen[var]
        print(f"{var}={default}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="ECS configuration toolbox (read-only, secret-safe).")
    sub = parser.add_subparsers(dest="command", required=True)

    p_val = sub.add_parser("validate-config", help="Validate an environment.")
    p_val.add_argument("env", nargs="?", default=None)
    p_val.add_argument("--check-secrets", action="store_true")

    p_all = sub.add_parser("validate-all", help="Validate all environments.")
    p_all.add_argument("--check-secrets", action="store_true")

    for tier in ("uat", "prod", "dr"):
        pt = sub.add_parser(f"validate-{tier}", help=f"Validate the {tier} environment.")
        pt.add_argument("--check-secrets", action="store_true")

    p_show = sub.add_parser("show-current-config", help="Show a resolved deployment profile.")
    p_show.add_argument("env", nargs="?", default=None)
    p_show.add_argument("--json", action="store_true")

    p_cmp = sub.add_parser("compare-envs", help="Diff two environments.")
    p_cmp.add_argument("env_a")
    p_cmp.add_argument("env_b")
    p_cmp.add_argument("--json", action="store_true")

    p_gen = sub.add_parser("generate-env-template", help="Emit a .env template for an environment.")
    p_gen.add_argument("env")

    args = parser.parse_args(argv)
    cmd = args.command

    if cmd == "validate-config":
        return _cmd_validate(args.env, check_secrets=args.check_secrets)
    if cmd == "validate-all":
        return _cmd_validate(None, check_secrets=args.check_secrets, all_envs=True)
    if cmd in ("validate-uat", "validate-prod", "validate-dr"):
        return _cmd_validate(cmd.split("-", 1)[1], check_secrets=args.check_secrets)
    if cmd == "show-current-config":
        return _cmd_show(args.env, as_json=args.json)
    if cmd == "compare-envs":
        return _cmd_compare(args.env_a, args.env_b, as_json=args.json)
    if cmd == "generate-env-template":
        return _cmd_generate_template(args.env)
    parser.error(f"unknown command: {cmd}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
