#!/usr/bin/env python3
"""Regenerate a reproducible ``requirements.lock`` from the current environment.

Pins the ECS dependency tree to the exact versions installed in the active
virtualenv (which must be a known-good env: app boots + targeted CI suite green).
Prints the lockfile to stdout so it can be redirected:

    python scripts/gen_requirements_lock.py > requirements.lock

This is the dependency-free fallback for environments without pip-tools. When
pip-tools IS available, ``pip-compile requirements.txt`` is preferred and produces
a fuller hash-pinned lock.
"""

from __future__ import annotations

import importlib.metadata as md
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Transitive deps we want pinned alongside the declared top-level requirements.
_EXTRA = [
    "starlette", "pydantic", "pydantic-core", "annotated-types", "anyio", "click",
    "h11", "httptools", "websockets", "certifi", "cryptography", "cffi",
    "pycparser", "requests", "urllib3", "charset-normalizer", "idna", "sniffio",
    "typing_extensions", "MarkupSafe", "et-xmlfile", "python-dateutil", "six",
    "dnspython",
]

HEADER = """\
# ===========================================================================
# ECS reproducible production lockfile  (generated by scripts/gen_requirements_lock.py)
# ===========================================================================
# Exact pinned versions of the ECS dependency tree from a known-good environment.
# Reproducible production/UAT install:   pip install -r requirements.lock
# requirements.txt keeps flexible (>=) pins; this lock is the pinned counterpart.
# Regenerate after editing requirements.txt (see the developer guide).
# ===========================================================================
"""


def _top_level_names() -> list[str]:
    names: list[str] = []
    req = ROOT / "requirements.txt"
    if req.is_file():
        for line in req.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Strip version specifiers + extras: "pyjwt[crypto]>=2" -> "pyjwt".
            name = re.split(r"[<>=!\[;]", line, maxsplit=1)[0].strip()
            if name:
                names.append(name)
    return names


def main() -> int:
    wanted = _top_level_names() + _EXTRA
    resolved: dict[str, str] = {}
    for name in wanted:
        try:
            resolved[name] = md.version(name)
        except md.PackageNotFoundError:
            continue  # optional / not installed in this env
    lines = [HEADER]
    for name in sorted(resolved, key=str.lower):
        lines.append(f"{name}=={resolved[name]}")
    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
