"""UC04 - Evidence dashboard and hash integrity check

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc04]


@pytest.mark.workbook_id("UC04-FT001")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft001(case_runner):
    """UC04-FT001: Connect to SharePoint source"""
    case_runner("UC04-FT001")


@pytest.mark.workbook_id("UC04-FT002")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft002(case_runner):
    """UC04-FT002: Collect evidence from SharePoint"""
    case_runner("UC04-FT002")


@pytest.mark.workbook_id("UC04-FT003")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft003(case_runner):
    """UC04-FT003: Connect to ServiceNow source"""
    case_runner("UC04-FT003")


@pytest.mark.workbook_id("UC04-FT004")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft004(case_runner):
    """UC04-FT004: Collect ServiceNow record evidence"""
    case_runner("UC04-FT004")


@pytest.mark.workbook_id("UC04-FT005")
@pytest.mark.priority_high
@pytest.mark.reporting
@pytest.mark.api
def test_uc04_ft005(case_runner):
    """UC04-FT005: Preserve source traceability"""
    case_runner("UC04-FT005")


@pytest.mark.workbook_id("UC04-FT006")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft006(case_runner):
    """UC04-FT006: Handle connector authorization failure"""
    case_runner("UC04-FT006")


@pytest.mark.workbook_id("UC04-FT007")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft007(case_runner):
    """UC04-FT007: Detect source changes"""
    case_runner("UC04-FT007")


@pytest.mark.workbook_id("UC04-FT008")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc04_ft008(case_runner):
    """UC04-FT008: Verify connector audit history"""
    case_runner("UC04-FT008")


@pytest.mark.workbook_id("UC04-FT009")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc04_ft009(case_runner):
    """UC04-FT009: Validate performance for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT009")


@pytest.mark.workbook_id("UC04-FT010")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc04_ft010(case_runner):
    """UC04-FT010: Validate notification mechanism for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT010")


@pytest.mark.workbook_id("UC04-FT011")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc04_ft011(case_runner):
    """UC04-FT011: Validate retry and recovery for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT011")


@pytest.mark.workbook_id("UC04-FT012")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc04_ft012(case_runner):
    """UC04-FT012: Validate security controls for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT012")


@pytest.mark.workbook_id("UC04-FT013")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc04_ft013(case_runner):
    """UC04-FT013: Validate evidence integrity for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT013")


@pytest.mark.workbook_id("UC04-FT014")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
@pytest.mark.positive
def test_uc04_ft014(case_runner):
    """UC04-FT014: Validate compliance mapping for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT014")


@pytest.mark.workbook_id("UC04-FT015")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc04_ft015(case_runner):
    """UC04-FT015: Validate concurrent user operations for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT015")


@pytest.mark.workbook_id("UC04-FT016")
@pytest.mark.priority_high
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.positive
def test_uc04_ft016(case_runner):
    """UC04-FT016: Validate dashboard/report visibility for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT016")


@pytest.mark.workbook_id("UC04-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc04_ft017(case_runner):
    """UC04-FT017: Validate retention and archival for Evidence dashboard and hash integrity check"""
    case_runner("UC04-FT017")
