"""Deterministic LLM use-case demo seed — physical evidence + rich observations.

Processes demo files through the EXISTING ECS path:
  physical file -> SNAPSHOT custody -> object store -> SQL metadata ->
  text extract/chunk -> embedding provider -> PGVector

Idempotent. Safe to call from the workbench; never raises to callers.
"""

from __future__ import annotations

import os
import threading
import zipfile
from io import BytesIO
from pathlib import Path
from typing import Any, Optional
from xml.etree import ElementTree as ET

_LOCK = threading.RLock()
_SEEDED = False
_LAST_REPORT: dict[str, Any] = {}

_REPO_ROOT = Path(__file__).resolve().parents[3]
_DEMO_DIR = _REPO_ROOT / "data" / "llm_usecase_demo"
_CANARY = "ECS-RAG-CANARY-7429"
_TARGET_EVIDENCE_COUNT = 30


def _slug(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "_" for ch in str(value or "")).strip("_")


def _build_pdf_bytes(text: str) -> bytes:
    payload = text.replace("(", "[").replace(")", "]").replace("\\", "/")
    stream = f"BT /F1 11 Tf 50 760 Td ({payload[:700]}) Tj ET"
    pdf = (
        "%PDF-1.4\n"
        "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n"
        "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n"
        "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj\n"
        f"4 0 obj << /Length {len(stream)} >> stream\n{stream}\nendstream endobj\n"
        "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n"
        "xref\n0 6\n0000000000 65535 f \n0000000010 00000 n \n0000000064 00000 n \n"
        "0000000121 00000 n \n0000000247 00000 n \n0000000000 00000 n \n"
        "trailer << /Size 6 /Root 1 0 R >>\nstartxref\n330\n%%EOF\n"
    )
    return pdf.encode("utf-8")


def _build_docx_bytes(lines: list[str]) -> bytes:
    content = "".join(f"<w:p><w:r><w:t>{line}</w:t></w:r></w:p>" for line in lines)
    document_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f"<w:body>{content}</w:body></w:document>"
    )
    types_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        "</Types>"
    )
    rels_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="word/document.xml"/>'
        "</Relationships>"
    )
    out = BytesIO()
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", types_xml)
        zf.writestr("_rels/.rels", rels_xml)
        zf.writestr("word/document.xml", document_xml)
    return out.getvalue()


def _build_file_bytes(spec: dict[str, Any]) -> bytes:
    ext = Path(spec["filename"]).suffix.lower()
    summary = (
        f"Application: {spec['application']}\n"
        f"Framework: {spec['framework']}\n"
        f"Control: {spec['control_id']}\n"
        f"Connector: {spec['source_connector']}\n"
        f"Evidence ID: {spec['evidence_id']}\n"
        f"Topic: {spec['topic']}\n"
    )
    if ext == ".json":
        body = {
            "evidence_id": spec["evidence_id"],
            "application": spec["application"],
            "framework": spec["framework"],
            "control_id": spec["control_id"],
            "connector": spec["source_connector"],
            "status": "Collected",
            "checks": ["evidence_integrity", "control_mapping", "custody_snapshot"],
            "notes": "Deterministic ECS demo evidence payload.",
        }
        if spec.get("canary"):
            body["canary"] = spec["canary"]
        import json
        return json.dumps(body, indent=2, sort_keys=True).encode("utf-8")
    if ext == ".pdf":
        return _build_pdf_bytes(summary + "Generated by ECS deterministic demo seeding.")
    if ext == ".docx":
        return _build_docx_bytes(
            [
                "ECS Audit Evidence Memo",
                f"Application: {spec['application']}",
                f"Framework: {spec['framework']}",
                f"Control: {spec['control_id']}",
                f"Connector Source: {spec['source_connector']}",
                f"Evidence ID: {spec['evidence_id']}",
            ],
        )
    return (summary + "Collection outcome: PASS\n").encode("utf-8")


def _extract_docx_text(content: bytes) -> str:
    """Extract plain text from DOCX main document part."""
    try:
        with zipfile.ZipFile(BytesIO(content), "r") as zf:
            xml_bytes = zf.read("word/document.xml")
    except Exception:
        return ""
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError:
        return ""
    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    paragraphs: list[str] = []
    for para in root.findall(".//w:p", ns):
        runs = para.findall(".//w:t", ns)
        text = "".join((node.text or "") for node in runs)
        if text:
            paragraphs.append(text)
    return "\n".join(paragraphs)


def _sanitize_docx_text_for_sql(text: str) -> str:
    return text.replace("\x00", "")


def _build_demo_evidence_catalog() -> tuple[dict[str, Any], ...]:
    from modules.audit_intelligence.engines import technology_control_mapping as mapping

    applications = ("Net Banking", "Mobile Banking", "Payments", "Treasury", "Card Operations")
    connectors = ("sharepoint_graph", "jira", "servicenow_cmdb", "sonarqube", "confluence", "github")
    formats = (
        ("pdf", "application/pdf"),
        ("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        ("json", "application/json"),
        ("txt", "text/plain"),
    )
    usable = [c for c in mapping.all_controls() if c.frameworks and c.control_id]
    usable.sort(key=lambda c: c.control_id)
    selected = usable[:_TARGET_EVIDENCE_COUNT]
    out: list[dict[str, Any]] = []
    for idx, control in enumerate(selected, start=1):
        ext, mime = formats[(idx - 1) % len(formats)]
        app = applications[(idx - 1) % len(applications)]
        connector = connectors[(idx - 1) % len(connectors)]
        frameworks = tuple(str(fw) for fw in control.frameworks if str(fw))
        fw = frameworks[0] if frameworks else ""
        topic = _slug(control.technology or "general")
        evidence_id = "EV-LLM-ENC-001" if idx == 1 else f"EV-DEMO-{idx:03d}"
        filename = (
            "netbanking_encryption_at_rest.json"
            if idx == 1
            else f"{_slug(app)}_{control.control_id.lower()}_{idx:02d}.{ext}"
        )
        out.append(
            {
                "evidence_id": evidence_id,
                "filename": filename,
                "application": app,
                "framework": fw,
                "frameworks": frameworks,
                "control_id": control.control_id,
                "mime_type": mime,
                "topic": topic,
                "source_connector": connector,
                "canary": _CANARY if idx == 1 else "",
            },
        )
    return tuple(out)


DEMO_EVIDENCE: tuple[dict[str, Any], ...] = _build_demo_evidence_catalog()

DEMO_OBSERVATIONS: tuple[dict[str, Any], ...] = (
    {
        "observation_id": "OBS-PCI-1000",
        "application": "Net Banking",
        "framework": "PCI DSS",
        "control_id": "PCI-8.3",
        "title": "MFA gap for privileged Net Banking operators",
        "finding_description": "Privileged break-glass accounts for Net Banking ops lack enforced MFA.",
        "description": "Privileged break-glass accounts for Net Banking ops lack enforced MFA.",
        "root_cause": "Legacy VPN path bypasses IdP MFA policy for emergency accounts.",
        "impact": "Unauthorized privileged access could alter payment routing configuration.",
        "recommendation": "Enforce MFA on all privileged Net Banking accounts including break-glass.",
        "remediation": "Enroll break-glass accounts in IdP MFA; remove VPN MFA exemption.",
        "observation_severity": "Critical",
        "risk": "Critical",
        "status": "Pending Upload",
        "missing_evidence": "MFA enrollment attestation missing",
        "evidence_type": "Attestation Pack",
        "owner": "R. Mehta",
        "due_date": "2026-06-20",
        "audit_impact": "Observation closure blocked",
    },
    {
        "observation_id": "OBS-PCI-1021",
        "application": "Net Banking",
        "framework": "PCI DSS",
        "control_id": "PCI-10.6",
        "title": "Daily SOC log review evidence incomplete",
        "finding_description": "SOC monitoring log export for Net Banking CHD systems is missing for the current period.",
        "description": "SOC monitoring log export for Net Banking CHD systems is missing for the current period.",
        "root_cause": "SIEM export job failed after index retention change.",
        "impact": "Cannot demonstrate daily log review for PCI-10.6 during QSA sampling.",
        "recommendation": "Restore SIEM use-case export and attach retention attestation.",
        "remediation": "Re-run Splunk export for Net Banking; attach retention attestation.",
        "observation_severity": "Critical",
        "risk": "High",
        "status": "Pending Upload",
        "missing_evidence": "SOC monitoring log export missing",
        "evidence_type": "Log Export",
        "owner": "R. Mehta",
        "due_date": "2026-06-05",
        "audit_impact": "Observation closure blocked",
    },
    {
        "observation_id": "OBS-PCI-1009",
        "application": "Net Banking",
        "framework": "PCI DSS",
        "control_id": "PCI-3.4",
        "title": "Encryption-at-rest attestation lag",
        "finding_description": "TDE attestation pack for Net Banking CHD tablespaces was stale at last review.",
        "description": "TDE attestation pack for Net Banking CHD tablespaces was stale at last review.",
        "root_cause": "Quarterly DB attestation schedule slipped after platform freeze.",
        "impact": "Risk of CHD stored without current encryption validation evidence.",
        "recommendation": "Submit current TDE status export and wallet custody attestation.",
        "remediation": "Attach netbanking_encryption_at_rest.json and close after auditor review.",
        "observation_severity": "Major",
        "risk": "High",
        "status": "Awaiting App Owner",
        "missing_evidence": "TDE attestation report expired",
        "evidence_type": "Attestation Pack",
        "owner": "R. Mehta",
        "due_date": "2026-06-18",
        "audit_impact": "Audit readiness reduced",
    },
    {
        "observation_id": "OBS-PCI-1018",
        "application": "Net Banking",
        "framework": "PCI DSS",
        "control_id": "PCI-4.1",
        "title": "TLS cipher inventory not refreshed",
        "finding_description": "Current TLS cipher inventory for Net Banking edge was not attached to the observation.",
        "description": "Current TLS cipher inventory for Net Banking edge was not attached to the observation.",
        "root_cause": "Config export automation pointed at pre-prod inventory path.",
        "impact": "Weak-cipher residual risk cannot be ruled out for customer sessions.",
        "recommendation": "Upload production Nginx TLS export with disabled weak ciphers.",
        "remediation": "Attach netbanking_tls_config.txt from production edge.",
        "observation_severity": "Major",
        "risk": "Medium",
        "status": "Overdue",
        "missing_evidence": "Firewall rule export not submitted",
        "evidence_type": "Configuration Export",
        "owner": "R. Mehta",
        "due_date": "2026-06-12",
        "audit_impact": "Audit readiness reduced",
    },
    {
        "observation_id": "OBS-VAPT-1003",
        "application": "Net Banking",
        "framework": "VAPT",
        "control_id": "VAPT-9",
        "title": "High finding pending retest evidence",
        "finding_description": "One high-severity web finding remains open pending retest pack.",
        "description": "One high-severity web finding remains open pending retest pack.",
        "root_cause": "Marketing microsite dependency upgrade delayed.",
        "impact": "External attack surface remains partially unvalidated.",
        "recommendation": "Attach latest Qualys WAS retest summary after jQuery upgrade.",
        "remediation": "Upload netbanking_vuln_scan.txt and mark finding remediating.",
        "observation_severity": "Major",
        "risk": "High",
        "status": "Awaiting App Owner",
        "missing_evidence": "Pen test retest evidence pending",
        "evidence_type": "Scan Report",
        "owner": "A. Sharma",
        "due_date": "2026-06-22",
        "audit_impact": "Audit readiness reduced",
    },
    {
        "observation_id": "OBS-ITPP-1004",
        "application": "Net Banking",
        "framework": "ITPP",
        "control_id": "IT-C-08",
        "title": "Backup restore proof not linked",
        "finding_description": "Latest Net Banking RMAN restore test log was not linked to the ITPP control folder.",
        "description": "Latest Net Banking RMAN restore test log was not linked to the ITPP control folder.",
        "root_cause": "Evidence uploaded to wrong SharePoint library.",
        "impact": "Continuity control may be sampled as missing during ITPP review.",
        "recommendation": "Relink restore test log to IT-C-08 and confirm RTO/RPO metrics.",
        "remediation": "Attach netbanking_backup_restore.txt under ITPP evidence pack.",
        "observation_severity": "Medium",
        "risk": "Medium",
        "status": "Pending Upload",
        "missing_evidence": "Backup restore test log missing",
        "evidence_type": "PDF Report",
        "owner": "K. Reddy",
        "due_date": "2026-06-25",
        "audit_impact": "Minor audit finding risk",
    },
)


def demo_dir() -> Path:
    return _DEMO_DIR


def canary_token() -> str:
    return _CANARY


def last_seed_report() -> dict[str, Any]:
    return dict(_LAST_REPORT)


def _seed_observations() -> int:
    from app import ecs_state
    from modules.governance.engines.missing_evidence_engine import _seed_registry

    _seed_registry()
    n = 0
    for row in DEMO_OBSERVATIONS:
        rec = dict(row)
        rec.setdefault("control", rec.get("control_id", ""))
        rec.setdefault("control_description", rec.get("finding_description", ""))
        rec.setdefault("requested_by", "Auditor_RK")
        rec.setdefault("remediation_owner", rec.get("owner", ""))
        rec.setdefault("prior_uploads", [])
        rec.setdefault("audit_comments", rec.get("recommendation", ""))
        rec.setdefault("rejection_reason", "")
        rec.setdefault("remediation_notes", rec.get("remediation", ""))
        rec.setdefault(
            "history",
            [{"date": "2026-05-01", "action": "Requested", "actor": "Auditor_RK"}],
        )
        ecs_state.missing_evidence_registry[rec["observation_id"]] = rec
        n += 1
    return n


def _ensure_object_store(root: Optional[Path] = None):
    from ecs_platform.storage import LocalObjectStore, get_object_store, reset_object_store, set_object_store

    # Prefer the existing configured object store (MinIO/S3) for real custody.
    # Only force a local store when a caller explicitly asks via object_store_root.
    if root is None:
        reset_object_store()
        return get_object_store()
    store = LocalObjectStore(root)
    set_object_store(store)
    return store


def _ensure_sql_persistence():
    from modules.audit_intelligence.services import persistence as pers
    from modules.audit_intelligence.services.sql_persistence import SqlAuditPersistence

    current = pers.get_persistence()
    if isinstance(current, SqlAuditPersistence):
        return current
    sql = SqlAuditPersistence()
    pers.set_persistence(sql)
    return sql


def _persist_postgres_evidence(spec: dict[str, Any], *, content: str, artifact: Any, source_url: str) -> None:
    """Persist seeded evidence into the existing PostgreSQL evidence repository."""
    from ecs_platform.repository.repository import EvidenceRepository

    metadata = dict(getattr(artifact, "metadata", {}) or {})
    metadata.update(
        {
            "evidence_id": str(getattr(artifact, "evidence_id", "") or spec.get("evidence_id", "")),
            "filename": str(getattr(artifact, "filename", "") or spec.get("filename", "")),
            "custody_mode": str(getattr(artifact, "custody_mode", "") or ""),
            "object_uri": str(getattr(artifact, "object_uri", "") or ""),
            "mime_type": str(getattr(artifact, "mime_type", "") or spec.get("mime_type", "")),
            "source_url": source_url,
            "source_connector": str(spec.get("source_connector") or "llm_usecase_demo"),
            "content_hash": str(getattr(artifact, "content_hash", "") or ""),
            "version": int(getattr(artifact, "version", 1) or 1),
        },
    )
    item = {
        "evidence_uid": str(getattr(artifact, "evidence_id", "") or spec.get("evidence_id", "")),
        "source_system": str(spec.get("source_connector") or "llm_usecase_demo"),
        "source_object_id": str(spec.get("evidence_id", "")),
        "object_type": str(spec.get("mime_type", "") or "text/plain"),
        "title": str(getattr(artifact, "filename", "") or spec.get("filename", "") or spec.get("evidence_id", "")),
        "content": content,
        "owner": "llm_usecase_demo_seed",
        "url": str(getattr(artifact, "object_uri", "") or source_url),
        "application": str(spec.get("application", "")),
        "metadata": metadata,
        "control_mapping": [str(spec.get("control_id", ""))] if spec.get("control_id") else [],
        "framework_mapping": [str(fw) for fw in (spec.get("frameworks") or ()) if str(fw)]
        or ([str(spec.get("framework", ""))] if spec.get("framework") else []),
    }
    repo = EvidenceRepository()
    repo.upsert_evidence(item)


def _ingest_one(
    spec: dict[str, Any],
    *,
    provider: Any = None,
    vector_store: Any = None,
) -> dict[str, Any]:
    from ecs_platform.evidence_indexing import index_evidence_version
    from modules.audit_intelligence.engines import evidence_repository as repo
    from modules.audit_intelligence.services import evidence_custody as custody

    path = _DEMO_DIR / spec["filename"]
    body = path.read_bytes()
    ext = Path(spec["filename"]).suffix.lower()
    if ext == ".docx":
        text = _sanitize_docx_text_for_sql(_extract_docx_text(body))
    else:
        text = body.decode("utf-8", errors="ignore")
    key = repo.make_evidence_key(spec["application"], spec["control_id"])
    version = 1
    existing = repo.get_latest(key)
    if existing and existing.evidence_id == spec["evidence_id"] and existing.custody_mode == "SNAPSHOT":
        source_url = f"file://{_DEMO_DIR.as_posix()}/{spec['filename']}"
        _persist_postgres_evidence(spec, content=text, artifact=existing, source_url=source_url)
        if provider is not None or vector_store is not None:
            idx = index_evidence_version(
                existing,
                normalized_text=text,
                snapshot_bytes=body,
                force=True,
                provider=provider,
                store=vector_store,
            )
        else:
            idx = {"ok": True, "skipped": True, "reason": "already_seeded"}
        return {
            "evidence_id": spec["evidence_id"],
            "filename": spec["filename"],
            "skipped": True,
            "version": existing.version,
            "object_uri": existing.object_uri,
            "indexing": idx,
        }

    if existing:
        version = int(existing.version) + 1

    source_connector = str(spec.get("source_connector") or "llm_usecase_demo")
    source_url = f"file://{_DEMO_DIR.as_posix()}/{spec['filename']}"
    cust = custody.resolve_custody(
        source_connector=source_connector,
        source_item_id=spec["evidence_id"],
        source_url=source_url,
        source_modified_at="2026-06-12T00:00:00Z",
        filename=spec["filename"],
        mime_type=spec["mime_type"],
        evidence_key=key,
        version=version,
        content=body,
        custody_mode=custody.CUSTODY_SNAPSHOT,
    )
    art = repo.store_evidence(
        control_id=spec["control_id"],
        content=text,
        asset_id=spec["application"],
        frameworks=(spec["framework"],),
        verdict="Collected",
        control_status="Evidence Available",
        evidence_quality=0.9,
        source="llm_usecase_demo",
        filename=spec["filename"],
        evidence_key=key,
        evidence_id=spec["evidence_id"],
        environment="Production",
        source_connector=source_connector,
        source_item_id=spec["evidence_id"],
        source_url=source_url,
        mime_type=spec["mime_type"],
        metadata={"topic": spec.get("topic", ""), "demo": "llm_usecase"},
        custody_mode=cust.custody_mode,
        source_modified_at="2026-06-12T00:00:00Z",
        object_uri=cust.object_uri,
        content_hash_override=cust.content_hash,
        size_bytes_override=cust.size_bytes,
    )
    _persist_postgres_evidence(spec, content=text, artifact=art, source_url=source_url)
    if provider is not None or vector_store is not None:
        idx = index_evidence_version(
            art,
            normalized_text=text,
            snapshot_bytes=body,
            force=True,
            provider=provider,
            store=vector_store,
        )
    else:
        idx = {"ok": True, "embedded_chunks": 0, "skipped": True, "reason": "default_hook"}
    return {
        "evidence_id": art.evidence_id,
        "filename": art.filename,
        "version": art.version,
        "object_uri": art.object_uri,
        "custody_mode": art.custody_mode,
        "content_hash": art.content_hash,
        "indexing": idx,
        "skipped": False,
    }


def _ensure_demo_files() -> None:
    _DEMO_DIR.mkdir(parents=True, exist_ok=True)
    for spec in DEMO_EVIDENCE:
        path = _DEMO_DIR / str(spec["filename"])
        if path.is_file():
            continue
        path.write_bytes(_build_file_bytes(spec))


def seed_llm_usecase_demo(
    *,
    force: bool = False,
    provider: Any = None,
    vector_store: Any = None,
    object_store_root: Optional[Path] = None,
    enable_sql: bool = True,
) -> dict[str, Any]:
    """Seed observations + physical evidence through the real ECS custody/index path."""
    global _SEEDED, _LAST_REPORT
    with _LOCK:
        if _SEEDED and not force:
            return dict(_LAST_REPORT)

        report: dict[str, Any] = {
            "ok": False,
            "observations": 0,
            "evidence_files": 0,
            "stored": [],
            "errors": [],
            "canary": _CANARY,
            "demo_dir": str(_DEMO_DIR),
        }
        prev_snap = os.environ.get("ECS_EVIDENCE_SNAPSHOT_ENABLED")
        prev_mode = os.environ.get("ECS_EVIDENCE_CUSTODY_MODE")
        prev_mime = os.environ.get("ECS_EVIDENCE_ALLOWED_MIME_TYPES")
        prev_wf = os.environ.get("AUDIT_WORKFLOW_ENABLED")
        try:
            os.environ["ECS_EVIDENCE_SNAPSHOT_ENABLED"] = "true"
            os.environ["ECS_EVIDENCE_CUSTODY_MODE"] = "SNAPSHOT"
            os.environ["ECS_EVIDENCE_ALLOWED_MIME_TYPES"] = (
                "application/pdf,"
                "application/json,"
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document,"
                "text/plain,text/csv"
            )
            if enable_sql:
                os.environ["AUDIT_WORKFLOW_ENABLED"] = "true"
                _ensure_sql_persistence()
            _ensure_object_store(object_store_root)
            report["observations"] = _seed_observations()

            _ensure_demo_files()

            for spec in DEMO_EVIDENCE:
                try:
                    stored = _ingest_one(spec, provider=provider, vector_store=vector_store)
                    report["stored"].append(stored)
                except Exception as exc:  # noqa: BLE001
                    report["errors"].append(f"{spec['evidence_id']}:{type(exc).__name__}:{exc}")
            report["evidence_files"] = len(report["stored"])
            report["ok"] = not report["errors"]
            _SEEDED = True
        except Exception as exc:  # noqa: BLE001
            report["errors"].append(f"seed_failed:{type(exc).__name__}:{exc}")
        finally:
            if prev_snap is None:
                os.environ.pop("ECS_EVIDENCE_SNAPSHOT_ENABLED", None)
            else:
                os.environ["ECS_EVIDENCE_SNAPSHOT_ENABLED"] = prev_snap
            if prev_mode is None:
                os.environ.pop("ECS_EVIDENCE_CUSTODY_MODE", None)
            else:
                os.environ["ECS_EVIDENCE_CUSTODY_MODE"] = prev_mode
            if prev_mime is None:
                os.environ.pop("ECS_EVIDENCE_ALLOWED_MIME_TYPES", None)
            else:
                os.environ["ECS_EVIDENCE_ALLOWED_MIME_TYPES"] = prev_mime
            if prev_wf is None:
                os.environ.pop("AUDIT_WORKFLOW_ENABLED", None)
            else:
                os.environ["AUDIT_WORKFLOW_ENABLED"] = prev_wf
            _LAST_REPORT = report
        return dict(report)


def ensure_seeded(**kwargs: Any) -> dict[str, Any]:
    """Best-effort lazy seed for workbench calls. Never raises."""
    try:
        return seed_llm_usecase_demo(**kwargs)
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "errors": [f"{type(exc).__name__}:{exc}"]}


def reset_seed_flag() -> None:
    """Test helper — allows re-seed in the same process."""
    global _SEEDED
    with _LOCK:
        _SEEDED = False
