"""UC13 - Cross-application compliance comparison

GENERATED by tests/functional/tools/generate_tests.py from registry/ecs_test_registry.json - do not edit by hand.
One function per workbook Functional Test ID; behaviour lives in orchestration.py and framework/ helpers.
"""

import pytest

pytestmark = [pytest.mark.functional, pytest.mark.uc13]


@pytest.mark.workbook_id("UC13-FT001")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft001(case_runner):
    """UC13-FT001: Onboard a new application"""
    case_runner("UC13-FT001")


@pytest.mark.workbook_id("UC13-FT002")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft002(case_runner):
    """UC13-FT002: Validate mandatory onboarding data"""
    case_runner("UC13-FT002")


@pytest.mark.workbook_id("UC13-FT003")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft003(case_runner):
    """UC13-FT003: Configure applicable frameworks/controls"""
    case_runner("UC13-FT003")


@pytest.mark.workbook_id("UC13-FT004")
@pytest.mark.priority_high
@pytest.mark.integration
@pytest.mark.api
def test_uc13_ft004(case_runner):
    """UC13-FT004: Configure evidence sources/connectors"""
    case_runner("UC13-FT004")


@pytest.mark.workbook_id("UC13-FT005")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft005(case_runner):
    """UC13-FT005: Reuse standard configuration"""
    case_runner("UC13-FT005")


@pytest.mark.workbook_id("UC13-FT006")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft006(case_runner):
    """UC13-FT006: Prevent duplicate application onboarding"""
    case_runner("UC13-FT006")


@pytest.mark.workbook_id("UC13-FT007")
@pytest.mark.priority_high
@pytest.mark.api
def test_uc13_ft007(case_runner):
    """UC13-FT007: Verify new application in downstream views"""
    case_runner("UC13-FT007")


@pytest.mark.workbook_id("UC13-FT008")
@pytest.mark.priority_high
@pytest.mark.api
@pytest.mark.database
def test_uc13_ft008(case_runner):
    """UC13-FT008: Audit onboarding changes"""
    case_runner("UC13-FT008")


@pytest.mark.workbook_id("UC13-FT009")
@pytest.mark.priority_high
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc13_ft009(case_runner):
    """UC13-FT009: Validate role-based access for Cross-application compliance comparison"""
    case_runner("UC13-FT009")


@pytest.mark.workbook_id("UC13-FT010")
@pytest.mark.priority_medium
@pytest.mark.performance
@pytest.mark.positive
def test_uc13_ft010(case_runner):
    """UC13-FT010: Validate performance for Cross-application compliance comparison"""
    case_runner("UC13-FT010")


@pytest.mark.workbook_id("UC13-FT011")
@pytest.mark.priority_medium
@pytest.mark.notification
@pytest.mark.negative
def test_uc13_ft011(case_runner):
    """UC13-FT011: Validate notification mechanism for Cross-application compliance comparison"""
    case_runner("UC13-FT011")


@pytest.mark.workbook_id("UC13-FT012")
@pytest.mark.priority_medium
@pytest.mark.dashboard
@pytest.mark.api
@pytest.mark.negative
def test_uc13_ft012(case_runner):
    """UC13-FT012: Validate data accuracy for Cross-application compliance comparison"""
    case_runner("UC13-FT012")


@pytest.mark.workbook_id("UC13-FT013")
@pytest.mark.priority_medium
@pytest.mark.integration
@pytest.mark.positive
def test_uc13_ft013(case_runner):
    """UC13-FT013: Validate retry and recovery for Cross-application compliance comparison"""
    case_runner("UC13-FT013")


@pytest.mark.workbook_id("UC13-FT014")
@pytest.mark.priority_medium
@pytest.mark.security
@pytest.mark.rbac
@pytest.mark.negative
def test_uc13_ft014(case_runner):
    """UC13-FT014: Validate security controls for Cross-application compliance comparison"""
    case_runner("UC13-FT014")


@pytest.mark.workbook_id("UC13-FT015")
@pytest.mark.priority_high
@pytest.mark.integrity
@pytest.mark.database
@pytest.mark.api
@pytest.mark.positive
def test_uc13_ft015(case_runner):
    """UC13-FT015: Validate evidence integrity for Cross-application compliance comparison"""
    case_runner("UC13-FT015")


@pytest.mark.workbook_id("UC13-FT016")
@pytest.mark.priority_high
@pytest.mark.concurrency
@pytest.mark.positive
def test_uc13_ft016(case_runner):
    """UC13-FT016: Validate concurrent user operations for Cross-application compliance comparison"""
    case_runner("UC13-FT016")


@pytest.mark.workbook_id("UC13-FT017")
@pytest.mark.priority_high
@pytest.mark.retention
@pytest.mark.positive
def test_uc13_ft017(case_runner):
    """UC13-FT017: Validate retention and archival for Cross-application compliance comparison"""
    case_runner("UC13-FT017")
